# Generated by Django 4.1 on 2022-08-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=300)),
                ("image", models.ImageField(upload_to="posts/images")),
                ("date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Publicacion",
                "verbose_name_plural": "Publicaciones",
            },
        ),
    ]
