# Generated by Django 4.1 on 2022-08-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("back", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Proyecto", "verbose_name_plural": "Proyectos"},
        ),
    ]
