# Generated by Django 4.1 on 2022-08-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back", "0002_alter_project_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="media/images/"),
        ),
    ]
